version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: memberdb
      MYSQL_USER: reactapp
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
       - ./database:/var/lib/mysql
       - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8086:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: P@ssw0rd     

  proxy:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./proxy
    ports:
      - "80:80"

  backend:
    build:
      context: "./backend"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST_IP: mysql_db
    ports:
      - "3001:3001"

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
